self.ui.tableWidget_2.setItem(row, col, QTableWidgetItem(str(r[row][col])))
                # self.ui.tableWidget_2.setItem(row, col, QTableWidgetItem(str(r[row][col])))
                # self.ui.tableWidget_2.setItem(row, col, QTableWidgetItem(str(r[row][col])))
                # self.ui.tableWidget_2.setItem(row, col, QTableWidgetItem(str(r[row][col])))
                # self.ui.tableWidget_2.setItem(row, col, QTableWidgetItem(str(r[row][col])))
                # self.ui.tableWidget_2.setItem(row, col, QTableWidgetItem(str(r[row][col])))
                # self.ui.tableWidget_2.setItem(row, col, QTableWidgetItem(str(r[row][col])))
                # self.ui.tableWidget_2.setItem(row, col, QTableWidgetItem(str(r[row][col])))
                # self.ui.tableWidget_2.setItem(row, col, QTableWidgetItem(str(r[row][col])))
